### PR TITLE
Fix flaky tests

### LINKED ISSUE #202: go test failure on master (segmentation violation)
### Your environment.
  - Version: 3b470331467299f1cb7d3b0b9a3955e396231521

### What did you do?

Ran `go test`

### What did you expect?

Test to pass

### What happened?

sam@samubuntu:~/Dev/pion/ice$ go test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x752230]

goroutine 91 [running]:
github.com/pion/ice/v2.(*Agent).handleInbound(0xc0000aea00, 0xc000088460, 0x904580, 0xc0000b0500, 0x8fa660, 0xc00028a030)
	/home/sam/Dev/pion/ice/agent.go:922 +0x800
github.com/pion/ice/v2.handleInboundCandidateMsg.func1(0xc0000aea00)
	/home/sam/Dev/pion/ice/candidate_base.go:113 +0x58
github.com/pion/ice/v2.(*Agent).run(0xc0000aea00, 0xc00044ef10, 0xc000112000, 0xc00028c000, 0x0)
	/home/sam/Dev/pion/ice/agent.go:168 +0x262
github.com/pion/ice/v2.handleInboundCandidateMsg(0x904580, 0xc0000b0500, 0xc00017c000, 0x70, 0x2000, 0x8fa660, 0xc00028a030, 0x902a40, 0xc00007c000)
	/home/sam/Dev/pion/ice/candidate_base.go:112 +0x538
github.com/pion/ice/v2.(*candidateBase).recvLoop(0xc0000b0500)
	/home/sam/Dev/pion/ice/candidate_base.go:97 +0xe1
created by github.com/pion/ice/v2.(*candidateBase).start
	/home/sam/Dev/pion/ice/candidate_base.go:81 +0xe0
exit status 2
FAIL	github.com/pion/ice/v2	4.349s

### PR DESCRIPTION
**Pull request by at-wat**
Avoid using uninitialized object on receiving packet.

Fix routine leak in TestTimeout.
Which seems caused timeout during routine leak test which requires max 10s.

### Reference issue
Fixes #202
Related #204

### CODE REVIEW

File: transport.go [hunk 1]
```diff
@@ -53,6 +53,8 @@ func (a *Agent) connect(ctx context.Context, isControlling bool, remoteUfrag, re
 		return nil, err
 	}
 
+	close(a.initializedCh)
```
Comment (Sean-Der) [inline transport.go:56]: We have three ways to communicate `initialized` now. Would it be possible to move them into one thing?

* `Agent.opened`
* `Agent.haveStarted` and `Agent.muHaveStarted`
*  `Agent. initializedCh`

Sorry lots of tech debt has added up. Happy to help aggressively refactor this.

Comment (at-wat) [reply transport.go:56]: `opened` seems never set and the same check is done using `haveStarted`. It can be simply removed.

As it requires to block until start, I'll move them into chan.

File: agent_test.go [hunk 2]
```diff
@@ -220,7 +229,7 @@ func runAgentTest(t *testing.T, config *AgentConfig, task func(a *Agent)) {
 
 func TestHandlePeerReflexive(t *testing.T) {
 	// Limit runtime in case of deadlocks
-	lim := test.TimeOut(time.Second * 2)
```
Comment (at-wat) [inline agent_test.go:223]: CheckRoutines takes at most 10s to wait routine exit.

**Comment by at-wat** [comment]
I tested one hour of iterations without error. (previously caused error within a few times of iterations)

**Comment by Sean-Der** [comment]
Amazing, thank you so much @at-wat! Thanks for cleaning up stuff so much.
