### PR TITLE
Candidate priority is incorrectly calculated

### LINKED ISSUE #14: Candidate.Priority() is completely wrong
https://github.com/pion/ice/blob/7245ac0866456f7c39a534f496d0f346ab7aad30/candidate.go#L212

`^` is XOR in Go, not exponentiation. `2^24 == 26`.

It should be `(1<<24) * c.Type().Preference()` or simply `c.Type().Preference() << 24`.

`uint16` is also not large enough to hold the correct value.

### PR DESCRIPTION
**Pull request by mjmac**
Some constants were being incorrectly generated using 2^N (XOR)
instead of 1 << N. This resulted in incorrect candidate priorities
being used to evaluate candidate pairs.

Resolves #14

### CODE REVIEW

File: candidatepair.go [hunk 1]
```diff
@@ -73,7 +73,7 @@ func (p *candidatePair) Priority() uint32 {
 		return 0
 	}
 
-	return (2^32)*min(g, d) + 2*max(g, d) + cmp(g, d)
+	return (2<<32)*uint64(min(g, d)) + uint64(2*max(g, d)+cmp(g, d))
```
Comment (maxhawkins) [inline candidatepair.go]: Shouldn't this be `1 << 32 `?

Comment (maxhawkins) [reply candidatepair.go]: `2*max(g, d)` overflows if `g == 1<<32-1`

Comment (mjmac) [reply candidatepair.go]: yep. fixed.

Comment (maxhawkins) [reply candidatepair.go]: I think there's still an overflow with `2*max(g, d)`

File: candidate.go [hunk 2]
```diff
@@ -202,16 +202,16 @@ func (c *Candidate) writeTo(raw []byte, dst *Candidate) (int, error) {
...
 	// The local preference MUST be an integer from 0 (lowest preference) to
 	// 65535 (highest preference) inclusive.  When there is only a single IP
 	// address, this value SHOULD be set to 65535.  If there are multiple
 	// candidates for a particular component for a particular data stream
 	// that have the same type, the local preference MUST be unique for each
 	// one.
-	return (2^24)*c.Type.Preference() +
-		(2^8)*c.LocalPreference +
-		(2^0)*(256-c.Component)
+	return (1<<24)*uint32(c.Type.Preference()) +
```
Comment (kixelated) [inline candidate.go]: `uint32(c.Type.Preference()) << 24` is the same result

Comment (mjmac) [reply candidate.go]: > `uint32(c.Type.Preference()) << 24` is the same result

Granted, but it's less readable IMO. Especially when comparing the implementation to the spec.
