### PR TITLE
Cancel Previous Gathering Routine On Restart

### LINKED ISSUE #280: ICE Agent can not be restarted when gathering
In recent versions of the Unnamed SFU, the client will restart ICE whenever the connection's ICE state goes into failed.  I'm occasionally getting the following error:

    ICE Agent can not be restarted when gathering

It happens somewhere in the code that handles incoming offers; I'd need to add more detailed logging in order to know which exact function triggers the error.  How do I avoid this problem?

### PR DESCRIPTION
**Pull request by wawesomeNOGUI**
#### Description

Updated ICE agent restart method to cancel the current gathering and then restart the candidate gathering process.

#### Reference issue

Fixes #280

### CODE REVIEW

**Comment by wawesomeNOGUI** [comment]
I haven’t gotten to test this yet, I’ll test it in a bit

File: examples/ping-pong/main_RestartTest.go [hunk 1]
```diff
@@ -0,0 +1,192 @@
...
+	}
+
+	remoteUfrag := <-remoteAuthChannel
+	remotePwd := <-remoteAuthChannel
+
+	if err = iceAgent.GatherCandidates(); err != nil {        //start gathering candidates
+		panic(err)                                        //will only find local because no STUN server
+	}
+
+	if err = iceAgent.Restart(localUfrag, localPwd); err != nil {
```
Comment (wawesomeNOGUI) [inline examples/ping-pong/main_RestartTest.go:140]: I tested the update to Restart by just adding a few calls to it. I'm not sure if this test is perfect, but I have confirmed that the Restart function can be called while there is a gatherer running and the peers can still connect. (I just added: a `fmt.Println("cancled")` after calling `agent.gatherCandidateCancel` in my testing to confirm it ran.)

File: examples/ICERestart/main_RestartTest.go [hunk 2]
```diff
@@ -0,0 +1,190 @@
...
+        }
+
+        remoteUfrag := <-remoteAuthChannel
+        remotePwd := <-remoteAuthChannel
+
+        if err = iceAgent.GatherCandidates(); err != nil { //start gathering candidates
+                panic(err) //will only find local because no STUN server
+        }
+
+        if err = iceAgent.Restart(localUfrag, localPwd); err != nil {
```
Comment (wawesomeNOGUI) [inline examples/ICERestart/main_RestartTest.go:140]: I tested the update to Restart by just adding a few calls to it in the example/ping-pong/main.go. I'm not sure if this test is perfect, but I have confirmed that the Restart function can be called while there is a gatherer running and the peers can connect. (I just added: a fmt.Println("cancled") after calling agent.gatherCandidateCancel in agent.go in my testing to confirm it ran.)

Comment (wawesomeNOGUI) [reply examples/ICERestart/main_RestartTest.go:140]: Actually, I just updated the agent_test.go instead, so we probably don't need this file.

**Review by stv0g — APPROVED** [review]
LGTM.

I've squashed and rebased the changes to the latest master.
