### PR TITLE
Fix relay candidate preference

### LINKED ISSUE #879: ICE doesn't enforce relay preference
The [CandidateRelay](https://github.com/pion/ice/blob/4da5bc14ec421ae1e075a087ef95af78eecbd98b/candidate_relay.go#L12C6-L12C20) implementation of [LocalPreference](https://github.com/pion/ice/blob/4da5bc14ec421ae1e075a087ef95af78eecbd98b/candidate_relay.go#L79) is currently not used.

### What did you do?
Added test that confirms that relay protocol doesn't affect candidate priority.
https://github.com/pion/ice/pull/878

### What did you expect?
I expected the relay protocol (udp or tcp) to be factored into the candidate priority calculation. Ideally, the implementation should consistently prioritize udp over tcp.

### PR DESCRIPTION
**Pull request by amanakin**
#### Description
This fixes the handling of relay preferences. Previously, `LocalPreference` for `CandidateRelay` was not being called, causing all relay protocols to have the same priority. This change introduces protocol-based preferences (UDP: 3, DTLS: 2, TCP: 1, TLS: 0).

#### Reference issue
Fixes #879

### CODE REVIEW

File: candidate_relay.go [hunk 1]
```diff
@@ -8,6 +8,14 @@ import (
 	"net/netip"
 )
 
+const (
+	// These preference values come from libwebrtc
+	// https://github.com/mozilla/libwebrtc/blob/1389c76d9c79839a2ca069df1db48aa3f2e6a1ac/p2p/base/port.h#L65
```
Comment (fippo) [inline candidate_relay.go]:
```suggestion
	// https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/p2p/base/turn_port.cc;l=96?q=turn_port.cc
```

Comment (amanakin) [reply candidate_relay.go]: Fixed

**Comment by amanakin** [comment]
@JoTurk Hey! Sure, happy to help. :) Regarding this PR, I've started a thread in discord for discussion. libwebrtc's preference for DTLS looks weird..

**Comment by JoTurk** [comment]
yeah i was reading the discord discussion, and libwebrtc impl.
sent the invite :)
